version: '3.8'

services:
  wekitsu-frontend:
    build:
      context: .
      dockerfile: Dockerfile
      x-bake:
        no-cache: false
        provenance: false
    ports:
      - "8080:80"
    restart: unless-stopped
    container_name: wekitsu-frontend
